### ISSUE TITLE
`stream` wait condition consumes output before assertion

### ISSUE THREAD

**Issue by autopp** [autopp/texest#77]
This test fails
```yaml
tests:
  - processes:
      proc1:
        command:
          - bash
          - '-c'
          - |
            trap 'echo goodbye >&2; exit 1' TERM
            echo hello
            while true; do true; done
        background:
          wait_for:
            type: stream
            pattern: hello
      proc2:
        command:
          - true
          - world
    expect:
      processes:
        proc1:
          stdout:
            eq: "hello\n" # "hello" is consumed by waiting
```
